# Generated by Django 3.0.7 on 2020-07-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
